/**
 * Build a WP7 submission-assist package (metadata only — no PII).
 * Cities supply underlying data; WP7 calculates KPIs.
 */

import { getAllWp7Datasets } from "@/data/wp7/adaptDataset";
import type { Wp7DatasetRecord } from "@/data/wp7/wp7Types";
import {
  WP7_CITY_KPI_MATRIX,
  WP7_COMPLIANCE_MATRIX,
  getCityComplianceSummary,
} from "./cityComplianceMatrix";
import { KPI_EVIDENCE_RULE_SUMMARIES } from "./kpiEvidenceRules";
import { ALL_CITIES } from "@/data/datasetMetadata";

export interface Wp7ExportPackage {
  manifest: {
    generatedAt: string;
    spec: string;
    purpose: string;
    cities: string[];
    citySummaries: Record<
      string,
      { ready: number; partial: number; missing: number; total: number }
    >;
    kpiScores: Array<{
      city: string;
      pilotId: string | null;
      kpiId: string;
      status: string;
      datasetIds: string[];
      notes: string[];
    }>;
  };
  datasets: Record<string, ReturnType<typeof serializeDataset>>;
  kpiEvidenceSummaryCsv: string;
  readme: string;
}

function serializeDataset(d: Wp7DatasetRecord) {
  return {
    id: d.id,
    city: d.city,
    pilotIds: d.pilotIds,
    title: d.title,
    linkedKpis: d.linkedKpis,
    wrongProxyForKpis: d.wrongProxyForKpis,
    universal: {
      ...d.universal,
      // Strip free-text contact from export if it looks like an email — keep role label only
      responsibleContact: d.universal.responsibleContact.includes("@")
        ? "[redacted — contact via responsibleOrg]"
        : d.universal.responsibleContact,
    },
    kpiEvidence: d.kpiEvidence,
    missingUniversalFields: d.missingUniversalFields,
    baseRegistry: {
      dataType: d.base.dataType,
      parserStatus: d.base.parserStatus,
      realDataStatus: d.base.realDataStatus,
      beforeAfterStatus: d.base.beforeAfterStatus,
      source: d.base.source,
      temporalCoverage: d.base.temporalCoverage,
    },
  };
}

function csvEscape(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function buildKpiEvidenceCsv(
  cells = WP7_COMPLIANCE_MATRIX.filter((c) => c.pilotId === null)
): string {
  const header = [
    "city",
    "pilotId",
    "kpiId",
    "status",
    "datasetIds",
    "notes",
  ].join(",");
  const rows = cells.map((c) =>
    [
      csvEscape(c.city),
      csvEscape(c.pilotId ?? "city-level"),
      csvEscape(c.kpiId),
      csvEscape(c.status),
      csvEscape(c.datasetIds.join("|")),
      csvEscape(c.notes.join("; ").slice(0, 500)),
    ].join(",")
  );
  return [header, ...rows].join("\n");
}

export function buildWp7Readme(): string {
  const rules = KPI_EVIDENCE_RULE_SUMMARIES.map(
    (r) =>
      `- ${r.kpiId} (${r.title}): ${r.notes}\n  Required: ${r.requiredEvidence.join("; ")}`
  ).join("\n");

  return `ELABORATOR WP7 Submission-Assist Package
==========================================

Spec: WP7 City Data Specification (FINAL January 2026)
Generated by the ELLABORATOR living-lab platform.

IMPORTANT
---------
- This package is submission-assist metadata for harmonisation.
- Cities supply underlying data + metadata; WP7 calculates the KPIs.
- Ready / Partial / Missing scores do NOT mean WP7 calculation is finished.
- Export contains aggregated metadata only (no respondent-level PII).

Package contents
----------------
- manifest.json          City summaries + KPI score rows
- datasets/*.json        One Wp7DatasetRecord per dataset (as object map)
- kpi-evidence-summary.csv
- readme.txt             This file

KPI evidence expectations
-------------------------
${rules}

Next steps for cities
---------------------
1. Fill missing universal metadata (GDPR, access rights, intervention codes, contacts).
2. Provide formal expansion-plan artifacts for KPI 1.1 (monitoring ≠ plan).
3. Provide heat (3.2B) and circular materials (3.2C) evidence where claimed.
4. Do not promote mock / CITY_DATA panel headlines to Ready.
`;
}

export function buildWp7ExportPackage(cityFilter?: string): Wp7ExportPackage {
  const datasets = getAllWp7Datasets().filter((d) =>
    cityFilter ? d.city === cityFilter : true
  );
  const cities = cityFilter ? [cityFilter] : [...ALL_CITIES];
  const kpiScores = WP7_COMPLIANCE_MATRIX.filter((c) =>
    cityFilter ? c.city === cityFilter : true
  ).map((c) => ({
    city: c.city,
    pilotId: c.pilotId,
    kpiId: c.kpiId,
    status: c.status,
    datasetIds: c.datasetIds,
    notes: c.notes,
  }));

  const citySummaries: Wp7ExportPackage["manifest"]["citySummaries"] = {};
  for (const city of cities) {
    citySummaries[city] = getCityComplianceSummary(city);
  }

  const datasetMap: Wp7ExportPackage["datasets"] = {};
  for (const d of datasets) {
    datasetMap[d.id] = serializeDataset(d);
  }

  const csvCells = (cityFilter
    ? WP7_COMPLIANCE_MATRIX.filter((c) => c.city === cityFilter)
    : WP7_COMPLIANCE_MATRIX
  ).filter((c) => c.pilotId === null);

  return {
    manifest: {
      generatedAt: new Date().toISOString(),
      spec: "WP7 City Data Specification FINAL January 2026",
      purpose:
        "Submission-assist package: underlying dataset metadata + compliance scores. WP7 calculates KPIs.",
      cities,
      citySummaries,
      kpiScores,
    },
    datasets: datasetMap,
    kpiEvidenceSummaryCsv: buildKpiEvidenceCsv(csvCells),
    readme: buildWp7Readme(),
  };
}

function downloadBlob(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Download package as a structured JSON bundle + CSV companion. */
export function downloadWp7Package(cityFilter?: string) {
  const pkg = buildWp7ExportPackage(cityFilter);
  const date = new Date().toISOString().slice(0, 10);
  const suffix = cityFilter
    ? `-${cityFilter.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`
    : "";

  const bundle = {
    "manifest.json": pkg.manifest,
    "datasets": pkg.datasets,
    "kpi-evidence-summary.csv": pkg.kpiEvidenceSummaryCsv,
    "readme.txt": pkg.readme,
  };

  downloadBlob(
    `wp7-submission-package${suffix}-${date}.json`,
    JSON.stringify(bundle, null, 2),
    "application/json;charset=utf-8"
  );

  downloadBlob(
    `wp7-kpi-evidence-summary${suffix}-${date}.csv`,
    pkg.kpiEvidenceSummaryCsv,
    "text/csv;charset=utf-8"
  );
}

export { WP7_CITY_KPI_MATRIX };
